# Generated by Django 3.2.4 on 2021-06-08 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('contact_phone', models.CharField(max_length=14, verbose_name='Telefone')),
                ('contact_email', models.EmailField(max_length=120, verbose_name='E-mail')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('technical_manager', models.CharField(max_length=255, verbose_name='Responsável técnico')),
            ],
            options={
                'verbose_name': 'Marketplace',
                'verbose_name_plural': 'Marketplaces',
            },
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(verbose_name='Endpoint')),
                ('secret_key', models.CharField(max_length=255)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace', to='mkt.marketplace')),
            ],
        ),
    ]
